from datetime import datetime, timedelta
from urllib.parse import urlencode


def create_google_calendar_link(block):
    """
    Create a Google Calendar draft event link for a recommended study block.

    This creates an all-day event on the recommended date.
    The user can choose the exact time inside Google Calendar.
    """

    date_value = block.get("date", "")
    course_name = block.get("course_name", "Course")
    task_type = block.get("task_type", "Study Block")
    task = block.get("task", "")
    duration = block.get("recommended_duration_minutes", "")
    priority = block.get("priority", "")
    reason = block.get("reason", "")
    week = block.get("week", "")
    day = block.get("day", "")

    if not date_value:
        return ""

    try:
        block_date = datetime.strptime(date_value, "%Y-%m-%d").date()
    except ValueError:
        return ""

    next_day = block_date + timedelta(days=1)

    title = f"{course_name}: {task_type}"

    details = (
        f"Task: {task}\n"
        f"Course: {course_name}\n"
        f"Task type: {task_type}\n"
        f"Week: {week}\n"
        f"Recommended day: {day}\n"
        f"Recommended date: {date_value}\n"
        f"Recommended duration: {duration} minutes\n"
        f"Priority: {priority}\n"
        f"Reason: {reason}\n\n"
        "Generated by SemesterOS.\n"
        "Choose an exact time that works for you."
    )

    params = {
        "action": "TEMPLATE",
        "text": title,
        "dates": f"{block_date.strftime('%Y%m%d')}/{next_day.strftime('%Y%m%d')}",
        "details": details,
    }

    return "https://calendar.google.com/calendar/render?" + urlencode(params)